WIP: Grant CRUD Role to dedicated-admins group
red-hat-data-services/odh-manifests pull request #144
Opened 2021-08-17 06:43 UTC by gmfrasca

2021-08-17 17:53 UTC, anishasthana requested changes
Can you link to the related JIRA issue in the PR?

2021-08-17 17:53 UTC, anishasthana commented on odh-common/base/kustomization.yaml
> +- fake_cm.yaml
oops

2021-08-17 17:53 UTC, anishasthana commented on osd-configs/README.md
> +To install Kafka add the following to the `KfDef` in your yaml file.
kafka?

2021-08-17 18:01 UTC, gmfrasca commented on osd-configs/README.md
> +To install Kafka add the following to the `KfDef` in your yaml file.
whooops.... :spaghetti: :no_good: 

fixed now

2021-08-17 18:02 UTC, gmfrasca commented on odh-common/base/kustomization.yaml
> +- fake_cm.yaml
fixed

2021-08-17 18:04 UTC, gmfrasca commented
PR: https://issues.redhat.com/browse/RHODS-1590

2021-08-17 19:01 UTC, anishasthana requested changes
Left one nit comment. Is this deployed anywhere / available as part of a rhods-operator image?

2021-08-17 19:01 UTC, anishasthana commented on osd-configs/README.md
> +A simple Kustomize App that provides utilities for running ODH on OpenShift Dedicated
You're going to hate me. Can you change `ODH` to `RHODS`?

2021-08-18 15:09 UTC, anishasthana approved these changes
I have verified that the roles and rolebindings are created. They also granted enough permissions to dedicated-admins that we were expecting.

2021-08-18 15:15 UTC, merged