Fix nb package version
red-hat-data-services/odh-manifests pull request #197
Opened 2022-01-26 12:55 UTC by maroroman

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-2425
- [ ] The Jira story is acked
- [ ] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

2022-01-26 14:12 UTC, lugi0 requested changes

2022-01-26 14:12 UTC, lugi0 commented on jupyterhub/notebook-images/overlays/additional/minimal-notebook-imagestream.yaml
> +      opendatahub.io/notebook-python-dependencies: '[{"name":"JupyterLab","version": "3.2"}, {"name": "Notebook","version": "6.0"}]'
Notebook should still be `6.4` rather than `6.0`

2022-01-27 18:56 UTC, crobby requested changes
As luca said, notebook should be 6.4 rather than 6.0

2022-01-28 13:35 UTC, lugi0 approved these changes
lgtm

2022-01-28 13:45 UTC, samuelvl commented
lgtm

2022-01-28 14:26 UTC, merged